name: 'Restore Cluster State'
description: 'Restores the clusters directory from the apicurio-testing-cache repository'
inputs:
  github-token:
    description: 'GitHub access token for API calls and accessing the cache repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Restore cluster state
      shell: bash
      run: |
        ./load-cache.sh --token "${{ inputs.github-token }}"
