apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    storage:
      type: kafkasql
      kafkasql:
        bootstrapServers: my-cluster-kafka-bootstrap:9092
    ingress:
      host: $APP_INGRESS_URL
    features:
      resourceDeleteEnabled: true
  ui:
    ingress:
      host: $UI_INGRESS_URL
