apiVersion: v1
kind: Service
metadata:
  name: postgresql-keycloak
  namespace: $NAMESPACE
  labels:
    app: postgresql-keycloak
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgresql-keycloak
  type: ClusterIP
