name: 'Save Cluster State'
description: 'Packages the clusters directory and saves it to the apicurio-testing-cache repository'
inputs:
  github-token:
    description: 'GitHub access token for API calls and pushing to the cache repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Package and save cluster state
      shell: bash
      run: |
        # Clone the cache repository if it doesn't already exist
        if [ ! -d "workflow-cache" ]; then
          git clone https://${{ inputs.github-token }}@github.com/Apicurio/apicurio-testing-cache.git workflow-cache
          cd workflow-cache
          # Configure git for the cache repository
          git config user.name "apicurio-ci"
          git config user.email "apicurio.ci@gmail.com"
          cd ..
        else
          echo "workflow-cache directory already exists, skipping clone"
        fi
        
        # Create a timestamp-based directory name
        RUN_DATE=$(date +%Y-%m-%d)
        CACHE_DIR="workflow-cache/runs/${{ github.run_id }}"
        mkdir -p "$CACHE_DIR"

        # Check if clusters directory exists and has content
        if [ -d "clusters" ] && [ "$(ls -A clusters)" ]; then
          echo "Removing openshift installer to minimize size of clusters.zip"
          rm -f clusters/$CLUSTER_NAME/openshift-install.tar.gz
          rm -f clusters/$CLUSTER_NAME/openshift-install

          echo "Packaging clusters directory..."
          zip -r clusters.zip clusters/
          # Move zip file to cache directory
          mv clusters.zip "$CACHE_DIR/"
          
          echo "Cluster state packaged as: $CACHE_DIR/clusters.zip"
        else
          echo "Warning: clusters directory is empty or doesn't exist, creating placeholder"
          touch "$CACHE_DIR/no-clusters-found.txt"
        fi
        
        # Commit and push cluster state to the cache repository
        cd workflow-cache
        git pull origin main
        git add .
        if git diff --cached --quiet; then
          echo "No cluster state changes to commit."
        else
          git commit -m "Save cluster state for workflow run ${{ github.run_id }}"
          git push origin main
        fi
        cd ..
