name: 'Commit Pod Logs'
description: 'Downloads pod logs and commits them to the repository'
inputs:
  cluster-name:
    description: 'Name of the cluster'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  job-name:
    description: 'Name of the current job'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download and commit pod logs
      shell: bash
      run: |
        WORK_DIR=".work"
        NAME="results-for-pod-logs"
        RESULTS_DIR="$WORK_DIR/$NAME"

        # Clone the results repository
        rm -rf $RESULTS_DIR
        git clone https://${{ inputs.github-token }}@github.com/Apicurio/apicurio-testing-results.git $RESULTS_DIR
        pushd .
        cd $RESULTS_DIR
        # Configure git for the results repository
        git config user.name "apicurio-ci"
        git config user.email "apicurio.ci@gmail.com"
        popd

        # Download pod logs
        ./download-pod-logs.sh --cluster ${{ inputs.cluster-name }} --namespace ${{ inputs.namespace }}

        BASE_DIR="."

        CLUSTER_NAME=${{ inputs.cluster-name }}
        NAMESPACE=${{ inputs.namespace }}
        LOGS_DIR="$BASE_DIR/logs/$CLUSTER_NAME/$NAMESPACE"

        # Create directory structure in the results repository
        RUN_DATE=$(date +%Y-%m-%d)
        JOB_DIR="$RESULTS_DIR/${RUN_DATE}-${{ github.run_id }}/${{ inputs.job-name }}/pod-logs"
        mkdir -p "$JOB_DIR"
        cp -r $LOGS_DIR/* "$JOB_DIR/" 2>/dev/null || true
        
        # Commit and push pod logs to the results repository
        pushd .
        cd $RESULTS_DIR
        git add .
        if git diff --cached --quiet; then
          echo "No pod logs to commit."
        else
          git commit -m "Add pod logs for job ${{ inputs.job-name }} from workflow run ${{ github.run_id }}"
          git pull origin main
          git push origin main
        fi
        popd

        rm -rf $RESULTS_DIR
