name: 'Cleanup Cluster State'
description: 'Deletes the previously saved cluster state from the apicurio-testing-cache repository'
inputs:
  github-token:
    description: 'GitHub access token for API calls and pushing to the cache repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Delete cluster state from cache
      shell: bash
      run: |
        WORK_DIR=".work"
        NAME="cache-for-cleanup"
        CACHE_DIR="$WORK_DIR/$NAME"

        # Clone the cache repository
        rm -rf $CACHE_DIR
        git clone https://${{ inputs.github-token }}@github.com/Apicurio/apicurio-testing-cache.git $CACHE_DIR
        pushd .
        cd $CACHE_DIR
        # Configure git for the cache repository
        git config user.name "apicurio-ci"
        git config user.email "apicurio.ci@gmail.com"
        git config pull.rebase true
        popd
        
        # Look for the cluster state directory to delete
        RUN_DIR="$CACHE_DIR/runs/${{ github.run_id }}"
        
        if [ -d "$RUN_DIR" ]; then
          echo "Found cluster state directory: $RUN_DIR"
          echo "Contents before deletion:"
          find "$RUN_DIR/"
          
          # Remove the entire run directory
          rm -rf "$RUN_DIR"
          echo "Cluster state directory deleted: $RUN_DIR"

          # Commit and push the deletion to the cache repository
          pushd .
          cd $CACHE_DIR
          git add .
          if git diff --cached --quiet; then
            echo "No cluster state changes to commit (directory may have already been deleted)."
          else
            git commit -m "Cleanup cluster state for workflow run ${{ github.run_id }}"
            for attempt in {1..5}; do
              if git pull origin main && git push origin main; then
                break
              else
                if [ $attempt -lt 5 ]; then
                  echo "Attempt $attempt failed. Retrying in $((attempt * 2)) seconds..."
                  sleep $((attempt * 2))
                else
                  echo "All retry attempts failed"
                  exit 1
                fi
              fi
            done
            echo "Cluster state cleanup committed and pushed"
          fi
          popd
          
        else
          echo "No cluster state found to cleanup for run ID ${{ github.run_id }}"
          echo "Expected directory: $RUN_DIR"
          echo "Available runs in cache:"
          ls -la $CACHE_DIR/runs/ 2>/dev/null || echo "No runs directory found"
        fi

        rm -rf $CACHE_DIR
        