name: 'Cleanup Cluster State'
description: 'Deletes the previously saved cluster state from the apicurio-testing-cache repository'
runs:
  using: 'composite'
  steps:

    - name: Delete cluster state from cache
      shell: bash
      run: |
        ./save-cache.sh -m "save test cache for workflow run ${{ github.run_id }}"
