apiVersion: v1
kind: Secret
metadata:
  name: mysql-database-password
type: Opaque
data:
  password: bXlzcWxwYXNzd29yZA==
---
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    ingress:
      host: $APP_INGRESS_URL
    features:
      resourceDeleteEnabled: true
    env:
      - name: APICURIO_STORAGE_SQL_KIND
        value: "mysql"
      - name: APICURIO_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/apicuriodb
      - name: APICURIO_DATASOURCE_USERNAME
        value: "mysqluser"
      - name: APICURIO_DATASOURCE_PASSWORD
        value: "mysqlpassword"
  ui:
    ingress:
      host: $UI_INGRESS_URL
