name: 'Checkout Code'
description: 'Checks out the repository'
inputs:
  access-token:
    description: 'Name of the cluster'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ inputs.access-token }}

    - name: Configure Git
      run: |
        git config --global user.name "apicurio-ci"
        git config --global user.email "apicurio.ci@gmail.com"
