name: 'Commit Integration Test Results'
description: 'Collects Maven Surefire test results and commits them to the repository'
inputs:
  cluster-name:
    description: 'Name of the cluster'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  job-name:
    description: 'Name of the current job'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Collect and commit integration test results
      shell: bash
      run: |
        WORK_DIR=".work"
        NAME="results-for-integration-tests"
        RESULTS_DIR="$WORK_DIR/$NAME"

        # Clone the results repository
        rm -rf $RESULTS_DIR
        git clone https://${{ inputs.github-token }}@github.com/Apicurio/apicurio-testing-results.git $RESULTS_DIR
        pushd .
        cd $RESULTS_DIR
        # Configure git for the results repository
        git config user.name "apicurio-ci"
        git config user.email "apicurio.ci@gmail.com"
        git config pull.rebase true
        popd
        
        # Create directory structure in the results repository
        RUN_DATE=$(date +%Y-%m-%d)
        JOB_DIR="$RESULTS_DIR/${RUN_DATE}-${{ github.run_id }}/${{ inputs.job-name }}"
        mkdir -p "$JOB_DIR/test-results"

        CLUSTER_NAME="${{ inputs.cluster-name }}"
        NAMESPACE="${{ inputs.namespace }}"

        BASE_DIR="."
        CLUSTER_DIR="$BASE_DIR/clusters/$CLUSTER_NAME"
        TESTS_DIR="$CLUSTER_DIR/namespaces/$NAMESPACE/tests"
        INTEGRATION_TESTS_DIR="$TESTS_DIR/integration/apicurio-registry/integration-tests"

        echo "Looking for integration test results in: $INTEGRATION_TESTS_DIR"
        echo "---"
        find $INTEGRATION_TESTS_DIR
        echo "---"

        # Collect Maven Surefire test results from integration-tests module
        if [ -d "$INTEGRATION_TESTS_DIR/target/surefire-reports" ]; then
          cp -r $INTEGRATION_TESTS_DIR/target/surefire-reports/* "$JOB_DIR/test-results/" 2>/dev/null || true
          echo "Copied Surefire test reports from $INTEGRATION_TESTS_DIR/target/surefire-reports/"
        fi

        # Also look for failsafe reports (for integration tests)
        if [ -d "$INTEGRATION_TESTS_DIR/target/failsafe-reports" ]; then
          mkdir -p "$JOB_DIR/test-results/failsafe-reports"
          cp -r $INTEGRATION_TESTS_DIR/target/failsafe-reports/* "$JOB_DIR/test-results/failsafe-reports/" 2>/dev/null || true
          echo "Copied Failsafe test reports from $INTEGRATION_TESTS_DIR/target/failsafe-reports/"
        fi

        # Commit and push integration test results to the results repository
        pushd .
        cd $RESULTS_DIR
        git add .
        if git diff --cached --quiet; then
          echo "No integration test results to commit."
        else
          git commit -m "Add integration test results for job ${{ inputs.job-name }} from workflow run ${{ github.run_id }}"
          for attempt in {1..5}; do
            if git pull origin main && git push origin main; then
              break
            else
              if [ $attempt -lt 5 ]; then
                echo "Attempt $attempt failed. Retrying in $((attempt * 2)) seconds..."
                sleep $((attempt * 2))
              else
                echo "All retry attempts failed"
                exit 1
              fi
            fi
          done
        fi
        popd

        rm -rf $RESULTS_DIR
