name: 'Commit UI Test Results'
description: 'Collects Playwright test results and commits them to the repository'
inputs:
  cluster-name:
    description: 'Name of the cluster'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  job-name:
    description: 'Name of the current job'
    required: true
  run-id:
    description: 'GitHub workflow run ID'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Collect and commit UI test results
      shell: bash
      run: |
        # Create workflow-results directory structure
        RUN_DATE=$(date +%Y-%m-%d)
        RESULTS_DIR="workflow-results/${RUN_DATE}-${{ inputs.run-id }}/${{ inputs.job-name }}"
        mkdir -p "$RESULTS_DIR/test-results"

        BASE_DIR="."
        CLUSTER_NAME=${{ inputs.cluster-name }}
        CLUSTER_DIR="$BASE_DIR/clusters/$CLUSTER_NAME"
        NAMESPACE=${{ inputs.namespace }}
        TESTS_DIR="$CLUSTER_DIR/namespaces/$NAMESPACE/tests"
        UI_TESTS_DIR="$TESTS_DIR/ui/apicurio-registry/ui/tests"

        echo "Looking for UI test results in: $UI_TESTS_DIR"
        echo "---"
        find $UI_TESTS_DIR
        echo "---"

        # Collect Playwright test results
        if [ -d "$UI_TESTS_DIR/playwright-report" ]; then
          cp -r $UI_TESTS_DIR/playwright-report/* "$RESULTS_DIR/test-results/" 2>/dev/null || true
          echo "Copied Playwright HTML report from $UI_TESTS_DIR/playwright-report/"
        fi

        # Collect test results JSON files
        if [ -d "$UI_TESTS_DIR/test-results" ]; then
          mkdir -p "$RESULTS_DIR/test-results/raw-results"
          cp -r $UI_TESTS_DIR/test-results/* "$RESULTS_DIR/test-results/raw-results/" 2>/dev/null || true
          echo "Copied Playwright raw test results from $UI_TESTS_DIR/test-results/"
        fi

        # Configure git and commit test results
        git pull origin main
        git add workflow-results
        if git diff --cached --quiet; then
          echo "No UI test results to commit."
        else
          git commit -m "Add UI test results for job ${{ inputs.job-name }} from workflow run ${{ inputs.run-id }}"
          git push origin main
        fi
