name: Test Apicurio Registry Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        description: >-
          Released version to test. This is used to select which operator version to install,
          currently from the upstream repository.
        required: true
      operator-image:
        type: string
        description: Override the operator image used when installing the operator (optional).
        required: false
      app-image:
        type: string
        description: Override the Apicurio Registry application/server image used by the operator (optional).
        required: false
      ui-image:
        type: string
        description: Override the Apicurio Registry UI image used by the operator (optional).
        required: false
      testsuite-git-ref:
        type: string
        description: >-
          Upstream Apicurio Registry test suite is used to run the tests. 
          This git reference (e.g. tag or branch) is used to checkout the test suite code.
        required: true
        default: main
      is-downstream:
        type: boolean
        description: >-
          Run the tests in downstream mode. Currently, it is only used in the UI tests 
          to check that the UI is productized.
        required: true
        default: false
      skip-cluster-installation:
        type: boolean
        description: Skip cluster installation
        required: true
        default: false

jobs:

  record-start-time:
    runs-on: ubuntu-latest
    outputs:
      start-time: ${{ steps.get-start-time.outputs.start-time }}
    steps:

      - name: Get Workflow Start Time
        id: get-start-time
        run: |
          START_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "start-time=$START_TIME" >> $GITHUB_OUTPUT
          echo "Workflow start time: $START_TIME"

  clusters:
    runs-on: ubuntu-latest
    needs: record-start-time
    strategy:
      fail-fast: false
      max-parallel: 1 # TODO: At the moment we can only run one cluster at a time.
      matrix:
        # cluster-version: [ "4.19", "4.14" ]
        cluster-version: [ "4.19" ]
        include:
          - cluster-version: "4.19"
            cluster-name: ci419
          - cluster-version: "4.14"
            cluster-name: ci414
    continue-on-error: true
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run on cluster
        uses: ./.github/workflows/test-cluster.yaml
        with:
          cluster-version: ${{ matrix.cluster-version }}
          cluster-name: ${{ matrix.cluster-name }}
          release-version: ${{ inputs.release-version }}
          operator-image: ${{ inputs.operator-image }}
          app-image: ${{ inputs.app-image }}
          ui-image: ${{ inputs.ui-image }}
          testsuite-git-ref: ${{ inputs.testsuite-git-ref }}
          is-downstream: ${{ inputs.is-downstream }}
          skip-cluster-installation: ${{ inputs.skip-cluster-installation }}

  save-workflow-metadata:
    name: Save Workflow Metadata
    runs-on: ubuntu-latest
    needs:
      - clusters
    if: always()
    timeout-minutes: 5
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log Workflow Start Time
        run: |
          echo "Workflow Start Time: ${{ needs.record-start-time.outputs.start-time }}"

      - name: Commit workflow metadata
        uses: ./.github/actions/commit-workflow-metadata
        with:
          workflow-start-time: ${{ needs.record-start-time.outputs.start-time }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
