name: Test RapiDAST Script
on:
  workflow_dispatch:
    inputs:
      test-url:
        description: URL of application to test
        required: true
      rapidast-version:
        description: RapiDAST version to run
        required: true
        default: development

jobs:
  run-rapidast:
    name: Run RapiDAST
    runs-on: ubuntu-22.04

    env:
      DAST_BASE_URL: ${{ github.event.inputs.test-url }}
      RAPIDAST_TAG: ${{ github.event.inputs.rapidast-version }}

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Required tools
        run: |
          python --version
          python3 --version
          java --version

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Apicurio Registry Operator
        run: |
          ./test-dast-scan.sh --url $DAST_BASE_URL --version $RAPIDAST_TAG
